words_with_hints = {
    "apple": "A sweet red or green fruit",
    "banana": "A long, yellow fruit",
    "cherry": "A small, round red fruit",
    "grapes": "Small round fruit that grows in bunches",
    "orange": "A citrus fruit rich in vitamin C",
    "strawberry": "A red fruit with tiny seeds on the outside",
    "watermelon": "A large green fruit with red juicy inside",
    "pineapple": "A tropical fruit with a spiky exterior",
    "elephant": "The largest land animal with a trunk",
    "giraffe": "Tallest land animal with a long neck",
    "kangaroo": "An animal that jumps and has a pouch",
    "dolphin": "A smart marine mammal that jumps in water",
    "tiger": "A big wild cat with orange and black stripes",
    "cheetah": "The fastest land animal",
    "panda": "A black and white bear that eats bamboo",
    "crocodile": "A large reptile that lives in water",
    "computer": "An electronic device used for programming",
    "laptop": "A portable computer",
    "keyboard": "A device used to type on a computer",
    "monitor": "A screen that displays computer output",
    "printer": "A device that prints documents",
    "mouse": "A device used to move the cursor",
    "software": "Programs and operating systems for a computer",
    "hardware": "Physical parts of a computer",
    "python": "A popular programming language",
    "javascript": "A scripting language for web development",
    "typescript": "A superset of JavaScript with types",
    "react": "A JavaScript library for building UIs",
    "angular": "A framework for building web applications",
    "django": "A Python web framework",
    "flask": "A lightweight Python web framework",
    "express": "A backend framework for Node.js",
    "sunshine": "Bright light from the sun",
    "moonlight": "The light of the moon",
    "thunderstorm": "A storm with lightning and thunder",
    "rainbow": "A multicolored arc in the sky",
    "hurricane": "A strong tropical storm",
    "earthquake": "Shaking of the ground due to tectonic movements",
    "blizzard": "A severe snowstorm",
    "airplane": "A flying vehicle with wings",
    "helicopter": "An aircraft with rotating blades",
    "motorcycle": "A two-wheeled motor vehicle",
    "bicycle": "A vehicle with two wheels powered by pedaling",
    "submarine": "A watercraft that can operate underwater",
    "spaceship": "A vehicle used for space travel",
    "satellite": "An object orbiting a planet",
    "football": "A sport played with a round ball",
    "cricket": "A sport played with a bat and ball",
    "basketball": "A sport where players shoot hoops",
    "badminton": "A racket sport played with a shuttlecock",
    "volleyball": "A sport where players hit a ball over a net",
    "baseball": "A bat-and-ball sport",
    "hockey": "A sport played with a stick and puck",
    "diamond": "A precious gemstone made of carbon",
    "emerald": "A green precious gemstone",
    "sapphire": "A blue precious gemstone",
    "ruby": "A red precious gemstone",
    "opal": "A gemstone with rainbow colors",
    "gold": "A shiny yellow metal",
    "silver": "A shiny gray metal",
    "platinum": "A valuable metal rarer than gold",
    "astronaut": "A person who travels to space",
    "scientist": "A person who studies science",
    "engineer": "A person who designs and builds things",
    "doctor": "A person who treats sick people",
    "teacher": "A person who educates students",
    "artist": "A person who creates paintings or drawings",
    "architect": "A person who designs buildings",
    "lawyer": "A person who practices law",
    "mountain": "A large natural elevation of the earth's surface",
    "valley": "A low area between hills or mountains",
    "canyon": "A deep valley with steep sides",
    "river": "A large flowing body of water",
    "waterfall": "Water falling from a height",
    "desert": "A dry area with little rain",
    "island": "A piece of land surrounded by water",
    "forest": "A large area covered with trees",
    "butterfly": "An insect with colorful wings",
    "honeybee": "An insect that makes honey",
    "mosquito": "A small insect that bites and sucks blood",
    "dragonfly": "An insect with two pairs of wings",
    "ladybug": "A small red and black insect",
    "firefly": "An insect that glows in the dark",
    "grasshopper": "An insect that jumps high",
    "birthday": "The anniversary of a person’s birth",
    "wedding": "A ceremony where two people get married",
    "festival": "A celebration with events and activities",
    "holiday": "A day off from work or school",
    "vacation": "A trip taken for relaxation",
    "celebration": "An event to mark a special occasion",
    "anniversary": "A yearly celebration of an event",
    "chocolate": "A sweet treat made from cocoa",
    "icecream": "A frozen dessert made from milk",
    "pancake": "A flat, round breakfast dish",
    "sandwich": "A meal made with bread and filling",
    "spaghetti": "Long thin pasta",
    "popcorn": "A snack made from heated corn",
    "cheesecake": "A dessert made from cheese and crust",
    "breeze": "A light wind",
    "whisper": "Speaking very softly",
    "mystery": "Something difficult to explain",
    "silence": "A complete absence of sound",
    "serenity": "A state of peace and calm",
    "twilight": "The time between sunset and night",
    "midnight": "The middle of the night",
    "sunrise": "When the sun appears in the morning"
}
